### ISSUE TITLE
Biased protocol

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.db.xm2vts#3]
Hi,

I was using the XM2VTS interface and I just realized that all protocols are biased.
If you check the command below, it is possible to observe that the same client is in the world, dev and eval sets.
Is that correct?
This is the original protocol or is it  a bug?

```python
import bob.db.xm2vts; db = bob.db.xm2vts.Database();
print db.clients(groups="world")
print db.clients(groups="dev")
print db.clients(groups="eval")
```

Thanks
Tiago

**Comment by laurentes** [comment]
Hi Tiago,

The protocols implemented are the ones described in this paper:
http://www.ee.surrey.ac.uk/CVSSP/xm2vtsdb/docs/messer-avbpa99.pdf

These protocols have few particularities:
- No world set
- Same enrollment samples for both the dev and eval sets

The original protocols are, hence, biased. And for the world set, the enrollment samples are used.

Best,

**Comment by tiagofrepereira2012** [comment]
Ok Laurent :-)

Thanks
